dist: trusty
sudo: false
language: node_js
node_js:
  - 10.16.0
cache:
  directories:
    - $HOME/.npm
branches:
  only:
    - master
    - dev
install:
  - npm i -g npm@6.9.0
  - npm install
  - npm ci
script:
  - npm run build
